import { randomBytes, randomUUID, createHash } from 'node:crypto';
import { mkdirSync,readFileSync,writeFileSync,renameSync,existsSync } from 'node:fs';
import path from 'node:path';
export const secret=()=>randomBytes(32).toString('hex');
export const hash=t=>createHash('sha256').update(t).digest('hex');
export function fail(status,message){throw Object.assign(new Error(message),{status});}
export class Store {
 constructor(dir){this.dir=dir;mkdirSync(dir,{recursive:true,mode:0o700});this.file=path.join(dir,'rooms.json');this.data=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):{rooms:{},sessions:{}};this.live=new Map();}
 save(){writeFileSync(this.file+'.tmp',JSON.stringify(this.data),{mode:0o600});renameSync(this.file+'.tmp',this.file);}
 session(roomId,personId,kind){const token=secret();this.data.sessions[hash(token)]={roomId,personId,kind,expiresAt:Date.now()+12*60*60*1000};this.save();return token;}
 auth(token,kind){const s=this.data.sessions[hash(token||'')];if(!s||(s.expiresAt&&s.expiresAt<Date.now())||kind&&s.kind!==kind)fail(401,'Geen geldige toegang. Meld je opnieuw aan.');const r=this.data.rooms[s.roomId];if(!r)fail(401,'Kamer bestaat niet.');return {s,r,p:r.members.find(m=>m.id===s.personId)};}
 create(name,proof){const id=randomUUID();const code=randomBytes(5).toString('hex').toUpperCase();const r={id,code,name,proof,members:[],driver:0,round:1,phase:'Plan',day:1,mode:'lesson',running:false,remaining:1500,deadline:null,evidence:[],handoffs:[],version:1};this.data.rooms[id]=r;const token=this.session(id,'facilitator','browser');return {token,roomId:id,code};}
 join(code,name){const r=Object.values(this.data.rooms).find(r=>r.code===code.toUpperCase());if(!r)fail(404,'Kamercode niet gevonden.');if(r.members.length>=5)fail(409,'Squad is vol (maximaal 5).');if(r.members.some(m=>m.name.toLowerCase()===name.toLowerCase()))fail(409,'Deze naam is al in gebruik. Gebruik je bestaande sessie of een onderscheidende naam.');const p={id:randomUUID(),name,help:false,quiz:null,route:'standard',lastMcp:null};r.members.push(p);r.version++;const token=this.session(r.id,p.id,'browser');return {token,roomId:r.id};}
 control(r,action,value,now=Date.now()){if(action==='start'){if(r.members.length<4)fail(409,'Wacht op minimaal 4 deelnemers.');if(!r.running){r.deadline=now+r.remaining*1000;r.running=true;}}else if(action==='pause'){r.remaining=this.remaining(r,now);r.running=false;r.deadline=null;}else if(action==='next'){if(r.members.length<4)fail(409,'Wacht op minimaal 4 deelnemers.');r.driver=(r.driver+1)%r.members.length;r.round++;r.running=false;r.remaining=1500;r.deadline=null;}else if(action==='phase'){if(!['Plan','Design','Build','Test','Deploy','Maintain'].includes(value))fail(400,'Onbekende fase.');r.phase=value;}else if(action==='day'){if(!Number.isInteger(value)||value<1||value>5)fail(400,'Kies supportdag 1–5.');r.day=value;}else if(action==='mode'){if(!['lesson','solo','squad','review'].includes(value))fail(400,'Onbekende werkvorm.');r.mode=value;}else fail(400,'Onbekende actie.');r.version++;this.save();}
 remaining(r,now=Date.now()){return r.running?Math.max(0,Math.ceil((r.deadline-now)/1000)):r.remaining;}
 view(r,s){return {id:r.id,name:r.name,code:r.code,round:r.round,phase:r.phase,day:r.day,mode:r.mode,running:r.running,remaining:this.remaining(r),serverTime:Date.now(),deadline:r.deadline,version:r.version,documentSlug:r.proof.slug,members:r.members.map((m,i)=>({id:m.id,name:m.name,role:i===r.driver?'Driver':'Navigator',online:(this.live.get(m.id)||0)>Date.now()-12000,help:m.help,...(s.personId==='facilitator'?{quiz:m.quiz}:{} )})),me:s.personId==='facilitator'?{id:'facilitator',name:'Facilitator',role:'Facilitator'}:{...r.members.find(m=>m.id===s.personId),role:r.members[r.driver]?.id===s.personId?'Driver':'Navigator'},evidence:r.evidence,handoffs:r.handoffs};}
}
