import React,{useEffect,useState,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {Users,BookOpen,Compass,Target,Sparkles,ClipboardCheck,Sun,Moon,ArrowRight,Clock,Play,Pause,RotateCw,HelpCircle,Check,Link,LogOut,Copy,ChevronRight,FileText} from 'lucide-react';
import {api,getToken,saveSession} from './api';
import {Knowledge,Coach,Lesson,Solo,Review,Route} from './panels';
import './style.css';
const phases=['Plan','Design','Build','Test','Deploy','Maintain'];
const nav=[['squad','Squad-room',Users],['route','Mijn route',Compass],['lesson','Les & quick check',BookOpen],['solo','Solo-missie',Target],['coach','Mijn leercoach',Sparkles],['review','Review & overdracht',ClipboardCheck]];
function App(){const [theme,setTheme]=useState(localStorage.getItem('academy-theme')||'dark');const [session,setSession]=useState(!!getToken());const [room,setRoom]=useState(null);const [view,setView]=useState('squad');const [error,setError]=useState('');const [connected,setConnected]=useState(false);const [busy,setBusy]=useState(false);
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('academy-theme',theme);},[theme]);
 useEffect(()=>{if(!session)return;let active=true;const poll=async()=>{try{const r=await api('state');if(active){setRoom(r);setConnected(true);}}catch(e){if(active){setConnected(false);setError(e.message);}}};api('resume',{}).then(poll).catch(e=>setError(e.message));const t=setInterval(poll,2000);return()=>{active=false;clearInterval(t);};},[session]);
 async function action(fn){setBusy(true);setError('');try{return await fn();}catch(e){setError(e.message);return null;}finally{setBusy(false);}}
 const themeButton=<button className="icon-button" aria-label={theme==='dark'?'Lichte modus':'Donkere modus'} onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?<Sun size={19}/>:<Moon size={19}/>}</button>;
 if(!session||!room)return <><header className="welcome-header"><Brand/>{themeButton}</header><Join ready={session} action={action} busy={busy} error={error} joined={()=>setSession(true)}/></>;
 const facilitator=room.me.role==='Facilitator';
 const control=(actionName,value)=>action(async()=>{const r=await api('control',{action:actionName,value});setRoom(r);});
 return <div className="app"><header className="topbar"><Brand/><div className="account"><span className={'connection '+(connected?'online':'offline')}><i/>{connected?'Room verbonden':'Roomverbinding verbroken'}</span>{themeButton}<span className="avatar small">{room.me.name.slice(0,2).toUpperCase()}</span><span>{room.me.name}</span><button className="icon-button" aria-label="Sessie verlaten" onClick={()=>action(async()=>{await api('logout',{});sessionStorage.removeItem('academy-token');sessionStorage.removeItem('academy-mcp-'+room.me.id);location.reload();})}><LogOut size={17}/></button></div></header>
 <aside className="sidebar"><nav aria-label="Hoofdnavigatie">{nav.map(([id,label,Icon])=><button key={id} className={view===id?'selected':''} onClick={()=>setView(id)}><Icon size={19}/>{label}</button>)}</nav><div className="sidebar-bottom"><span>Samen leren.</span><span>Beter bouwen.</span><strong>Echte impact.</strong><hr/><small>2 klasdagen · 5 supportdagen</small></div></aside>
 <main><div className="room-heading"><div><p className="muted">Supportdag {room.day} · {room.day<=2?'Begeleid':room.day===3?'Samen met coaching':room.day===4?'Met hints':'Zelfstandig'}</p><h1>{room.name}</h1></div><div className="round"><span>Ronde {room.round} · {room.running?'Praktijk':room.remaining===0?'Tijd is om':'Gepauzeerd'}</span><strong><Clock size={22}/><Timer room={room}/></strong></div></div>
 <div className="sdlc" aria-label="Software development lifecycle">{phases.map((p,i)=><React.Fragment key={p}><div className={p===room.phase?'active':''}><span>{p}</span></div>{i<5&&<span className="phase-line"/>}</React.Fragment>)}</div>
 {error&&<div className="error" role="alert">{error}<button onClick={()=>setError('')} aria-label="Melding sluiten">×</button></div>}
 {facilitator&&<div className="facilitator-controls"><strong>Facilitator</strong><button disabled={busy||!connected} onClick={()=>control(room.running?'pause':'start')}>{room.running?<Pause size={16}/>:<Play size={16}/>} {room.running?'Pauzeren':'Start timer'}</button><button disabled={busy||!connected} onClick={()=>control('next')}><RotateCw size={16}/>Volgende ronde</button><label>Fase<select value={room.phase} onChange={e=>control('phase',e.target.value)}>{phases.map(p=><option key={p}>{p}</option>)}</select></label><label>Dag<select value={room.day} onChange={e=>control('day',Number(e.target.value))}>{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><label>Werkvorm<select value={room.mode} onChange={e=>control('mode',e.target.value)}><option value="lesson">Les</option><option value="solo">Solo</option><option value="squad">Squad</option><option value="review">Review</option></select></label></div>}
 <div className="workspace"><section className="primary">{view==='squad'&&<Document room={room} theme={theme}/ >}{view==='route'&&<Route room={room} onNavigate={setView}/ >}{view==='lesson'&&<Lesson room={room} action={action} busy={busy}/ >}{view==='solo'&&<Solo room={room} action={action} busy={busy} onNavigate={setView}/ >}{view==='coach'&&<Coach room={room} action={action}/ >}{view==='review'&&<Review room={room} action={action} busy={busy}/ >}</section>
 <aside className="right-rail"><section className="panel roster"><div className="panel-heading"><h2>Jouw squad <span>({room.members.length}/5)</span></h2><Users size={17}/></div>{room.members.length===0&&<p className="muted">Wacht op je squad. Deel de kamercode om te beginnen.</p>}{room.members.map(m=><div className="member" key={m.id}><span className="avatar">{m.name.slice(0,2).toUpperCase()}</span><div><strong>{m.name}{m.id===room.me.id?' (jij)':''}</strong><small className={m.role==='Driver'?'cyan':''}>{m.role}</small></div><span className={'presence '+(m.online?'present':'')} title={m.online?'Recent actief':'Geen recente activiteit'}/>{m.help&&<HelpCircle size={17} className="cyan" aria-label="Hulp gevraagd"/>}</div>)}<div className="room-code"><small>Kamercode</small><button onClick={()=>action(()=>navigator.clipboard.writeText(room.code))} title="Kopieer kamercode">{room.code}<Copy size={14}/></button></div>{room.members.length<4&&<small className="muted">De praktijk start vanaf 4 deelnemers.</small>}</section>
 <section className="panel contribution"><FileText size={20}/><h2>Jouw bijdrage</h2><p>{facilitator?'Bewaak het tempo en bespreek het bewijs. Jij start de timer en roteert de driver.':room.me.role==='Driver'?'Verwerk het gezamenlijke besluit in de intent. Spreek hardop uit wat je verandert.':'Onderzoek één aanname. Stel een gerichte vraag of voeg onderbouwd commentaar toe.'}</p><small className="muted">Werkvorm: {({lesson:'Les & quick check',solo:'Individuele praktijk',squad:'Squad-synthese',review:'Review & overdracht'})[room.mode]}</small></section>
 <button className="gradient coach-cta" onClick={()=>setView('coach')}><Sparkles size={18}/>Vraag je leercoach<ArrowRight size={17}/></button>{!facilitator&&<button className="help-button" onClick={()=>action(()=>api('help',{}))}><HelpCircle size={16}/>{room.me.help?'Hulp gevraagd · intrekken':'Vraag de facilitator om hulp'}</button>}
 </aside></div><footer>Een gedeelde intent. Kleine stappen. Bewijs dat je kunt uitleggen.</footer></main></div>;
}
function Brand(){return <div className="brand">AetherLink <span>Academy</span></div>;}
function Join({ready,action,busy,error,joined}){const [create,setCreate]=useState(false);return <main className="join"><div className="join-copy"><p className="muted">Samen leren · samen bouwen · groeien</p><h1>Klaar voor je<br/><span>missie?</span></h1><p>Werk met je squad en je eigen Claude Code.<br/>Van een heldere intent naar werk dat je kunt uitleggen.</p><div className="join-principles"><span><Users/>Eén squad</span><span><FileText/>Gedeelde intent</span><span><Sparkles/>Je eigen leercoach</span></div></div><section className="join-form panel"><h2>{create?'Start een squad':'Welkom bij je squad'}</h2><p className="muted">{create?'Alleen voor de facilitator. De startsleutel staat lokaal bij de server.':'Vul je naam en de kamercode van je facilitator in.'}</p><form onSubmit={e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.currentTarget));action(async()=>{const result=await api(create?'create':'join',data);saveSession(result);joined();});}}><label>{create?'Squadnaam':'Je naam'}<input name="name" required maxLength={50} placeholder={create?'Squad Orion':'Bijv. Sam'}/></label><label>{create?'Facilitator-startsleutel':'Kamercode'}<input name={create?'hostKey':'code'} required type={create?'password':'text'} autoComplete="off" placeholder={create?'Lokale startsleutel':'Bijv. 8A2F…'}/></label><button className="gradient" disabled={busy}>{busy?'Verbinden…':create?'Maak squad':'Deelnemen'}<ArrowRight size={18}/></button></form>{error&&<p className="error" role="alert">{error}</p>}<button className="text-button" onClick={()=>setCreate(!create)}>{create?'Ik ben deelnemer':'Ik ben facilitator'}</button>{ready&&<p className="muted">Bestaande sessie herstellen…</p>}<small>Geen Anthropic API-key nodig. Gebruik je eigen ingelogde Claude Code.</small></section></main>;}
function Timer({room}){const [now,setNow]=useState(Date.now());const offset=useRef(0);useEffect(()=>{offset.current=room.serverTime-Date.now();},[room.serverTime]);useEffect(()=>{const t=setInterval(()=>setNow(Date.now()),500);return()=>clearInterval(t);},[]);const seconds=room.running?Math.max(0,Math.ceil((room.deadline-now-offset.current)/1000)):room.remaining;return <>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</>;}
function Document({room,theme}){const frame=useRef(null);const [state,setState]=useState('Editor laden…');useEffect(()=>{localStorage.setItem('proof-share-viewer-name',room.me.name);},[room.me.name]);useEffect(()=>{const update=()=>{try{const win=frame.current?.contentWindow;const d=win?.document;if(!d?.body)return;d.documentElement.dataset.academyTheme=theme;let style=d.getElementById('academy-style');if(!style){style=d.createElement('style');style.id='academy-style';d.head.appendChild(style);}style.textContent=`:root{--font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;--font-size:16px;--line-height:1.7;--bg-color:${theme==='dark'?'#0c1928':'#ffffff'};--text-color:${theme==='dark'?'#e3ecfa':'#14243a'};--code-bg:${theme==='dark'?'#172b43':'#eff4fa'};--blockquote-color:${theme==='dark'?'#b7c7df':'#42536a'}}body{background:var(--bg-color)!important;color:var(--text-color)!important} .milkdown,.ProseMirror{color:var(--text-color)!important;font-family:var(--font-family)!important} #editor{padding:24px 36px!important} .ProseMirror h1{font-size:26px!important}.ProseMirror h2{font-size:18px!important;margin-top:26px!important} #share-banner{display:none!important;position:sticky!important;top:0!important;left:0!important;transform:none!important;width:100%!important;margin:0!important;border-radius:0!important;background:var(--bg-color)!important;color:var(--text-color)!important;box-shadow:none!important;padding:8px 16px!important} #share-banner .share-pill-agent-btn,#share-banner .share-pill-share-btn,#share-banner .share-pill-title,#share-banner .share-pill-sep,#share-banner>a{display:none!important} #share-banner button[aria-label=\"Share options\"]{display:none!important} #share-banner *{color:var(--text-color)!important} #share-banner .share-pill-status-inline{display:flex!important} #editor{padding-top:20px!important}`;
 const editable=d.querySelector('[contenteditable="true"]');const sync=d.querySelector('.share-pill-status-inline .status-label')?.textContent?.trim();if(sync)setState(({Saved:'Proof verbonden · wijzigingen opgeslagen',Saving:'Proof · wijzigingen opslaan…',Connecting:'Proof · verbinden…',Offline:'Proof offline · controleer je verbinding',Syncing:'Proof · synchroniseren…'})[sync]||('Proof · '+sync));else if(editable)setState('Editor geopend · synchronisatie nog niet bevestigd');else if(d.body.innerText.includes('error')||d.body.innerText.includes('Not found'))setState('Proof kon niet laden');}catch{setState('Proof-status niet beschikbaar');}};update();const t=setInterval(update,1500);return()=>clearInterval(t);},[theme]);return <section className="panel document"><div className="document-heading"><div><h2>Onze intent</h2><p>Eén doorlopend document voor het hele team.</p></div><span><FileText size={15}/>Gedeeld document · Proof</span></div><div className="document-status"><i/>{state}</div><iframe ref={frame} key={room.documentSlug} src={'/d/'+room.documentSlug} title="Gedeelde Proof-intent"/><div className="document-foot"><span>Driver verwerkt · navigators lezen en geven feedback</span><small>Alle squadleden kunnen samenwerken in dit document.</small></div></section>;}
createRoot(document.getElementById('root')).render(<App/>);
